##
# Configuration
##
OUTPUT_DIR ?= $(realpath $(dir $(lastword ${MAKEFILE_LIST})))
TEXBIN ?= pdflatex
TEX_FLAGS?=-file-line-error -output-directory ${OUTPUT_DIR}
# -file-line-error
#	  Print error messages in the form file:line:error which is sim‐
#	  ilar to the way many compilers format them.
#-output-directory directory
#	  Write  output files in directory instead of the current direc‐
#	  tory.  Look up input files in directory first, the  along  the
#	  normal search path.

RESOLUTION?=600
DVIBIN ?=	dvipdfmx
PAPER ?= letter
DVI_FLAGS_ += -p ${PAPER}
#       -p  paper
#            Select the papersize  by  name  (e.g.,  letter,  legal,  ledger,
#            tabloid, a3, a4, or a5 )
DVI_FLAGS_ += -r ${RESOLUTION}
#       -r  size
#           Set  resolution  of  bitmapped  fonts  to  size  dots  per inch.
#           Bitmapped fonts are generated by  the  Kpathsea  library,  which
#           uses  Metafont.  Bitmapped fonts are included as Type 3 fonts in
#           the PDF output file.  Default is 600.
DVI_FLAGS_ += -vvvv
#       -v   Increase  verbosity.   Results  of  the -v option are cumulative
#            (e.g., -vv increases the verbosity by two increments).   Maximum
#            verbosity is four.
LEFT_MARGIN?=1.0in
DVI_FLAGS_ += -x ${LEFT_MARGIN}
#       -x x_offset
#            Set the left margin to x_offset.  The  default  left  margin  is
#            1.0in.   The  dimension may be specified in any units understood
#            by TeX (e.g., bp, pt, in, cm).
TOP_MARGIN?=1.0in
DVI_FLAGS_ += -x ${TOP_MARGIN}
#       -y y_offset
#            Set the top margin to  y_offset.   The  default  top  margin  is
#            1.0in.   The  dimension may be specified in any units understood
#            by TeX (e.g., bpt, pt, in, cm).
PDF_COMPRESSION?=9
DVI_FLAGS_ += -z ${PDF_COMPRESSION}
#       -z number
#            Set the compression  level  to  compression_level.   Compression
#            levels  range from 0 (no compression) to 9 (maximum compression)
#            and correspond to the values understood by zlib; default is 9.

DVI_FLAGS_ += -E
#       -E   Always try to embed fonts, ignoring licensing flags, etc.


##
# Dragons
##
MK:= $(lastword ${MAKEFILE_LIST})
TEX:=$(patsubst %.mk,%.tex,${MK})
DVI:=$(patsubst %.tex,%.dvi,${TEX})
PS:=$(patsubst %.tex,%.ps,${TEX})

PDF:=$(patsubst %.tex,%.pdf,${TEX})

DVI_FLAGS?=${DVI_FLAGS_}
DVIPDF:=$(patsubst %.tex,%.dvi.pdf,${TEX})
PDFBW:=$(patsubst %.tex,%_bw.pdf,${TEX})
PSPDF:=$(patsubst %.tex,%.ps.pdf,${TEX})
DVIPS:=$(patsubst %.tex,%.dvi.ps,${TEX})

ALL+=${PDF} ${DVIPDF} ${PDFBW}

# 5 works.
# time make -j1
# real	0m0.559s
# user	0m0.500s
# sys	0m0.059s

# time make -j8
# real	0m0.268s
# user	0m0.419s
# sys	0m0.082s
${PDF}: ${TEX}
	${TEXBIN} ${TEX_FLAGS} -output-format pdf ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format pdf ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format pdf ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format pdf ${^}

${DVI}: ${TEX}
	${TEXBIN} ${TEX_FLAGS} -output-format dvi ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format dvi ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format dvi ${^}
	${TEXBIN} ${TEX_FLAGS} -output-format dvi ${^}

${PDFBW}: ${DVI}
	${DVIBIN} ${DVIFLAGS} -o ${@} -c ${^}
#  -c 		Ignore color specials (for B&W printing)

${DVIPDF}: ${DVI}
	${DVIBIN} ${DVIFLAGS} -o ${@} ${^}

${DVIPS}: ${DVI}
	dvips -o ${@} ${^}
